export const SHOW_ERROR = 'SHOW_ERROR'

export const POA_SET_META_DATA = 'POA_GET_META_DATA'
export const POA_SET_ADDRESS_BALANCE = 'POA_SET_ADDRESS_BALANCE'
export const POA_SET_METAMASK_BALANCE = 'POA_SET_METAMASK_BALANCE'
