export const SHOW_ERROR = 'SHOW_ERROR'

export const POA_SET_TOKEN_DETAILS = 'POA_SET_TOKEN_DETAILS'
export const POA_SET_ADDRESS_BALANCE = 'POA_SET_ADDRESS_BALANCE'
export const POA_SET_METAMASK_BALANCE = 'POA_SET_METAMASK_BALANCE'
export const POA_SET_BUY_LOADING = 'POA_SET_BUY_LOADING'
export const POA_UNSET_BUY_LOADING = 'POA_UNSET_BUY_LOADING'
export const POA_SET_AVAILABLE = 'POA_SET_AVAILABLE'
